module.exports = {
  revert: "\x1b[0m",
  colourBlack: "\x1b[30m",
  colourRed: "\x1b[31m",
  colourGreen: "\x1b[32m",
  colourYellow: "\x1b[33m",
  colourBlue: "\x1b[34m",
  colourMagenta: "\x1b[35m",
  colourCyan: "\x1b[36m",
  colourWhite: "\x1b[37m",
  colourGrey: '\x1b[90m',

  backgroundBlack: "\x1b[40m",
  backgroundRed: "\x1b[41m",
  backgroundGreen: "\x1b[42m",
  backgroundYellow: "\x1b[43m",
  backgroundBlue: "\x1b[44m",
  backgroundMagenta: "\x1b[45m",
  backgroundCyan: "\x1b[46m",
  backgroundWhite: "\x1b[47m",
  backgroundBrightBlack: '\x1b[100m',
  backgroundGrey: this.backgroundBrightBlack,

  textBold: "\x1b[1m",
  textDim: "\x1b[2m",
  textItalic: "\x1b[3m",
  textUnderline: "\x1b[4m",
  textStrikeThrough: "\x1b[9m",
};
